# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mdddb
spring.datasource.username=postgres
spring.datasource.password=UN6N1=VH")``r+_ykB4Z
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT — replace secret with a secure 256-bit hex value in production
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
